import {
  Sparkles, FileSpreadsheet, TrendingUp, ShieldCheck, DollarSign,
  Building2, Sliders, ChevronRight, Play, Plus, Search, Calendar,
  BarChart3, Layers, FileText, CheckCircle2, Clock, AlertTriangle, Boxes,
  Calculator, Recycle, ShoppingCart, Flame, Truck, Wrench, FileCheck, HardHat,
  Radio, Shield, KeyRound, MapPin, User, Users, Activity, Tag, ShieldAlert
} from 'lucide-react'

import { CONSTRUCTION_REPORT_CATEGORIES } from './reportCategories'
import {
  getExecutiveSummaryReport,
  getStockVarianceReport,
  getAuditComplianceReport,
  getAssetHealthTrendReport,
  getMaintenanceCostReport,
  getSiteComparisonReport,
  getWarrantyRadarReport,
  getIdleRadarReport,
  getStatutoryComplianceReport,
  getScrapYieldReport,
  getConsumablesBurnReport,
  getFreightLogisticsReport,
  getOperatorSafetyReport,
  getProcurementPipelineReport,
  getGenericReportAdapter
} from './reports'

export { CONSTRUCTION_REPORT_CATEGORIES as REPORT_CATEGORIES }

export const ALL_REPORTS = [
  // ── 1. Executive & Project Overview ──
  {
    id: 'executive-summary',
    title: 'EXECUTIVE SUMMARY',
    category: 'executive',
    categoryLabel: 'Macro Portfolio',
    icon: Sparkles,
    color: '#0ea5e9',
    description: 'Macro enterprise portfolio valuation, total maintenance spend, audit compliance rates, and active anomalies.',
    fetcher: getExecutiveSummaryReport,
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'site-comparison',
    title: 'SITE COMPARISON & BENCHMARKING',
    category: 'executive',
    categoryLabel: 'Multi-Site',
    icon: Building2,
    color: '#06b6d4',
    description: 'Cross-site comparison of total asset counts, portfolio valuation (₹), variance values, and open ticket loads.',
    fetcher: getSiteComparisonReport,
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-ytd-summary',
    title: 'YTD SUMMARY REPORT',
    category: 'executive',
    categoryLabel: 'Year-to-Date Audit',
    icon: Calendar,
    color: '#10b981',
    description: 'Year-to-date additions, disposals, depreciation, maintenance spend, and net valuation changes.',
    fetcher: (params) => getGenericReportAdapter('asset-ytd-summary', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-current-valuation',
    title: 'TOTAL CURRENT ASSET VALUATION REPORT',
    category: 'executive',
    categoryLabel: 'Valuation Audit',
    icon: DollarSign,
    color: '#10b981',
    description: 'Gross book value, accumulated depreciation, net book value, and salvage valuation across all categories.',
    fetcher: (params) => getGenericReportAdapter('asset-current-valuation', params),
    permission: 'reports.financial',
    supportedFilters: ['site', 'category'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-valuation-chart',
    title: 'ASSET VALUATION CHART',
    category: 'executive',
    categoryLabel: 'Valuation Distribution',
    icon: BarChart3,
    color: '#3b82f6',
    description: 'Graphical valuation breakdown by site, category, and asset class.',
    fetcher: (params) => getGenericReportAdapter('asset-valuation-chart', params),
    permission: 'reports.financial',
    supportedFilters: ['site', 'category'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-register-summary',
    title: 'ASSET REGISTER SUMMARY REPORT',
    category: 'executive',
    categoryLabel: 'Register Overview',
    icon: Layers,
    color: '#6366f1',
    description: 'High-level summary of active, idle, under maintenance, disposed, and lost assets.',
    fetcher: (params) => getGenericReportAdapter('asset-register-summary', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'category'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },

  // ── 2. Fixed Assets ──
  {
    id: 'asset-valuation-journey',
    title: 'ASSET VALUATION JOURNEY',
    category: 'fixed_assets',
    categoryLabel: 'Capital Lifecycle',
    icon: TrendingUp,
    color: '#8b5cf6',
    description: 'Track asset lifecycle from acquisition cost to accumulated depreciation, revaluations, and net book value.',
    fetcher: (params) => getGenericReportAdapter('asset-valuation-journey', params),
    permission: 'reports.financial',
    supportedFilters: ['site', 'category', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-disposal',
    title: 'DISPOSAL REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Decommissioning',
    icon: Recycle,
    color: '#ef4444',
    description: 'Track decommissioned assets, salvage proceeds, net book value, and net gain/loss on disposal (₹).',
    fetcher: (params) => getGenericReportAdapter('asset-disposal', params),
    permission: 'reports.financial',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'department-depreciation',
    title: 'DEPARTMENT DEPRECIATION REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Dept Financials',
    icon: Calculator,
    color: '#8b5cf6',
    description: 'Departmental depreciation schedule showing opening value, additions, period depreciation, and closing book value.',
    fetcher: (params) => getGenericReportAdapter('department-depreciation', params),
    permission: 'reports.financial',
    supportedFilters: ['site', 'department'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'product-depreciation',
    title: 'PRODUCT DEPRECIATION REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Product Depreciation',
    icon: Boxes,
    color: '#0ea5e9',
    description: 'Depreciation breakdown by product model, acquisition cost, and remaining useful life.',
    fetcher: (params) => getGenericReportAdapter('product-depreciation', params),
    permission: 'reports.financial',
    supportedFilters: ['category'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-additions',
    title: 'ADDITION REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Capital Additions',
    icon: Plus,
    color: '#22c55e',
    description: 'Newly capitalized assets, acquisition dates, purchase orders, and vendor allocations.',
    fetcher: (params) => getGenericReportAdapter('asset-additions', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-register-details',
    title: 'ASSET REGISTER DETAILS REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Full Master Register',
    icon: FileText,
    color: '#06b6d4',
    description: 'Complete master asset register with codes, serial numbers, categories, custodians, and acquisition costs.',
    fetcher: (params) => getGenericReportAdapter('asset-register-details', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'category'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-new-register-details',
    title: 'ASSET NEW REGISTER DETAILS REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Recent Additions',
    icon: CheckCircle2,
    color: '#84cc16',
    description: 'Detailed listing of all assets added into the register during the selected date range.',
    fetcher: (params) => getGenericReportAdapter('asset-new-register-details', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-revaluation',
    title: 'ASSET REVALUATION REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Revaluation Audit',
    icon: TrendingUp,
    color: '#a855f7',
    description: 'Audit history of asset book value revaluations, impairment losses, and fair value adjustments.',
    fetcher: (params) => getGenericReportAdapter('asset-revaluation', params),
    permission: 'reports.financial',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-age-report',
    title: 'ASSET AGE REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Age Distribution',
    icon: Clock,
    color: '#f59e0b',
    description: 'Equipment age buckets (<1 yr, 1-3 yrs, 3-5 yrs, 5-10 yrs, >10 yrs) to identify replacement needs.',
    fetcher: (params) => getGenericReportAdapter('asset-age-report', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'category'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-status-report',
    title: 'ASSET STATUS REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Operational Status',
    icon: ShieldCheck,
    color: '#22c55e',
    description: 'Status distribution: Active, In Maintenance, Idle, Disposed, Lost, and In Transit.',
    fetcher: (params) => getGenericReportAdapter('asset-status-report', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'category'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-transaction-report',
    title: 'ASSET TRANSACTION REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Audit Trail',
    icon: Activity,
    color: '#6366f1',
    description: 'Historical audit trail of all asset modifications, status updates, and assignment changes.',
    fetcher: (params) => getGenericReportAdapter('asset-transaction-report', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-allocation-report',
    title: 'ASSET ALLOCATION REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Custodian Allocation',
    icon: User,
    color: '#06b6d4',
    description: 'Assets allocated to specific project sites, departments, and field engineers.',
    fetcher: (params) => getGenericReportAdapter('asset-allocation-report', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'department'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-lifespan-analysis',
    title: 'ASSET LIFESPAN ANALYSIS REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Expected vs Actual',
    icon: TrendingUp,
    color: '#10b981',
    description: 'Evaluates expected useful life against actual operating age to guide replacement cycles.',
    fetcher: (params) => getGenericReportAdapter('asset-lifespan-analysis', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'category'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-scrap-analysis',
    title: 'ASSET SCRAP ANALYSIS REPORT',
    category: 'fixed_assets',
    categoryLabel: 'End of Life',
    icon: Recycle,
    color: '#ef4444',
    description: 'Deep-dive analysis of assets flagged for scrap, expected salvage value (₹), and scrap history.',
    fetcher: getScrapYieldReport,
    permission: 'reports.financial',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'all-asset-report',
    title: 'ALL ASSET REPORT',
    category: 'fixed_assets',
    categoryLabel: 'Complete Dataset',
    icon: FileSpreadsheet,
    color: '#3b82f6',
    description: 'Complete un-filtered asset dataset for comprehensive data extraction.',
    fetcher: (params) => getGenericReportAdapter('all-asset-report', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'category'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-list-report',
    title: 'ASSET LIST',
    category: 'fixed_assets',
    categoryLabel: 'Operational List',
    icon: FileText,
    color: '#10b981',
    description: 'Clean operational asset list optimized for site supervisors and field engineers.',
    fetcher: (params) => getGenericReportAdapter('asset-list-report', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },

  // ── 3. Equipment & Maintenance ──
  {
    id: 'maintenance-kpi-dashboard',
    title: 'MAINTENANCE KPI DASHBOARD',
    category: 'maintenance',
    categoryLabel: 'Maintenance Scorecard',
    icon: Activity,
    color: '#ef4444',
    description: 'Key maintenance KPIs: MTTR, MTBF, Availability %, PM Compliance %, and backlog count.',
    fetcher: (params) => getGenericReportAdapter('maintenance-kpi-dashboard', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'gauge',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'maintenance-summary',
    title: 'MAINTENANCE SUMMARY',
    category: 'maintenance',
    categoryLabel: 'Executive Maintenance',
    icon: Wrench,
    color: '#0ea5e9',
    description: 'Executive maintenance summary: total work orders, resolved tickets, parts spend, and average downtime.',
    fetcher: (params) => getGenericReportAdapter('maintenance-summary', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'work-order-backlog',
    title: 'WORK ORDER BACKLOG REPORT',
    category: 'maintenance',
    categoryLabel: 'Backlog Aging',
    icon: AlertTriangle,
    color: '#d97706',
    description: 'Open work orders backlog aging analysis: pending >7 days, >14 days, and >30 days.',
    fetcher: (params) => getGenericReportAdapter('work-order-backlog', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'work-orders-list',
    title: 'WORK ORDERS LIST REPORT',
    category: 'maintenance',
    categoryLabel: 'Work Orders Register',
    icon: FileText,
    color: '#06b6d4',
    description: 'Master work order register with priority, assigned technician, asset code, and status.',
    fetcher: (params) => getGenericReportAdapter('work-orders-list', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'all-wo-detail',
    title: 'ALL WORK ORDERS DETAIL REPORT',
    category: 'maintenance',
    categoryLabel: 'Complete Work Orders',
    icon: FileSpreadsheet,
    color: '#3b82f6',
    description: 'Detailed work order dataset containing all historical and active maintenance tickets.',
    fetcher: (params) => getGenericReportAdapter('all-wo-detail', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'open-wo-detail',
    title: 'OPEN WORK ORDERS DETAIL REPORT',
    category: 'maintenance',
    categoryLabel: 'Open Tickets',
    icon: Clock,
    color: '#f59e0b',
    description: 'Detailed breakdown of active open work orders needing technician intervention.',
    fetcher: (params) => getGenericReportAdapter('open-wo-detail', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'overdue-wo-detail',
    title: 'OVERDUE WORK ORDERS DETAIL REPORT',
    category: 'maintenance',
    categoryLabel: 'SLA Breach',
    icon: AlertTriangle,
    color: '#ef4444',
    description: 'Work orders past due date with SLA breach duration and assigned supervisor.',
    fetcher: (params) => getGenericReportAdapter('overdue-wo-detail', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'closed-wo-detail',
    title: 'CLOSED WORK ORDERS DETAIL REPORT',
    category: 'maintenance',
    categoryLabel: 'Resolved Tickets',
    icon: CheckCircle2,
    color: '#22c55e',
    description: 'Detailed register of resolved and verified work orders.',
    fetcher: (params) => getGenericReportAdapter('closed-wo-detail', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'technician-performance',
    title: 'TECHNICIAN PERFORMANCE REPORT',
    category: 'maintenance',
    categoryLabel: 'Technician Scorecard',
    icon: CheckCircle2,
    color: '#84cc16',
    description: 'Technician performance scorecard: completed work orders, average resolution hours, and SLA compliance rate %.',
    fetcher: (params) => getGenericReportAdapter('technician-performance', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'wo-time-consumption',
    title: 'WORK ORDER TIME CONSUMPTION REPORT',
    category: 'maintenance',
    categoryLabel: 'Labor Hours',
    icon: Clock,
    color: '#ec4899',
    description: 'Technician labor hours consumed per work order and asset class.',
    fetcher: (params) => getGenericReportAdapter('wo-time-consumption', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'wo-cost-report',
    title: 'WORK ORDER COST REPORT',
    category: 'maintenance',
    categoryLabel: 'WO Expenditure',
    icon: DollarSign,
    color: '#10b981',
    description: 'Overall work order financial spend trend analysis.',
    fetcher: (params) => getGenericReportAdapter('wo-cost-report', params),
    permission: 'reports.financial',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-wo-cost',
    title: 'ASSET WORK ORDER COST REPORT',
    category: 'maintenance',
    categoryLabel: 'Equipment WO Cost',
    icon: DollarSign,
    color: '#8b5cf6',
    description: 'Cumulative work order cost per individual asset code.',
    fetcher: (params) => getGenericReportAdapter('asset-wo-cost', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset_maintenance_cost',
    title: 'ASSET MAINTENANCE COST REPORT',
    category: 'maintenance',
    categoryLabel: 'Financials',
    icon: DollarSign,
    color: '#8b5cf6',
    description: 'Repair cost distribution by priority, site, vendor billing analysis, and high-maintenance equipment candidates.',
    fetcher: getMaintenanceCostReport,
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-maint-summary',
    title: 'ASSET MAINTENANCE SUMMARY REPORT',
    category: 'maintenance',
    categoryLabel: 'Equipment Summary',
    icon: Wrench,
    color: '#3b82f6',
    description: 'Summary of maintenance history per asset equipment code.',
    fetcher: (params) => getGenericReportAdapter('asset-maint-summary', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-maint-report',
    title: 'ASSET MAINTENANCE REPORT',
    category: 'maintenance',
    categoryLabel: 'Equipment Maintenance',
    icon: FileText,
    color: '#6366f1',
    description: 'Detailed equipment maintenance log with parts used and costs.',
    fetcher: (params) => getGenericReportAdapter('asset-maint-report', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'wo-completion-rate',
    title: 'WORK ORDER COMPLETION RATE',
    category: 'maintenance',
    categoryLabel: 'Overall SLA Rate',
    icon: ShieldCheck,
    color: '#22c55e',
    description: 'Enterprise overall work order completion rate % gauge.',
    fetcher: (params) => getGenericReportAdapter('wo-completion-rate', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'gauge',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'scheduled-vs-unplanned-downtime',
    title: 'SCHEDULED VS UNPLANNED DOWNTIME',
    category: 'maintenance',
    categoryLabel: 'Downtime Comparison',
    icon: Activity,
    color: '#ef4444',
    description: 'Compare planned PM downtime hours against unexpected breakdown downtime.',
    fetcher: (params) => getGenericReportAdapter('scheduled-vs-unplanned-downtime', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-mttr-report',
    title: 'ASSET MTTR REPORT',
    category: 'maintenance',
    categoryLabel: 'Mean Time to Repair',
    icon: Clock,
    color: '#f97316',
    description: 'Mean Time To Repair (MTTR) calculation in hours per asset and category.',
    fetcher: (params) => getGenericReportAdapter('asset-mttr-report', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-mtbf-report',
    title: 'ASSET MTBF REPORT',
    category: 'maintenance',
    categoryLabel: 'Mean Time Between Failures',
    icon: Activity,
    color: '#ef4444',
    description: 'Mean Time Between Failures (MTBF) operating hours metric evaluating equipment reliability.',
    fetcher: (params) => getGenericReportAdapter('asset-mtbf-report', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-downtime-hits',
    title: 'ASSET DOWNTIME HITS REPORT',
    category: 'maintenance',
    categoryLabel: 'Breakdown Frequency',
    icon: AlertTriangle,
    color: '#d97706',
    description: 'Frequency count of breakdown events per equipment unit.',
    fetcher: (params) => getGenericReportAdapter('asset-downtime-hits', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'assets-downtime-availability',
    title: 'ASSETS DOWNTIME & AVAILABILITY REPORT',
    category: 'maintenance',
    categoryLabel: 'Operational Availability',
    icon: ShieldCheck,
    color: '#22c55e',
    description: 'Overall equipment effectiveness OEE and availability percentage ((Scheduled - Downtime)/Scheduled * 100).',
    fetcher: (params) => getGenericReportAdapter('assets-downtime-availability', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'gauge',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'fault-breakage-report',
    title: 'FAULT / BREAKAGE REPORT',
    category: 'maintenance',
    categoryLabel: 'Fault Analysis',
    icon: ShieldAlert,
    color: '#ef4444',
    description: 'Categorized breakage log: mechanical wear, operator error, electrical fault, or hydraulic leak.',
    fetcher: (params) => getGenericReportAdapter('fault-breakage-report', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-breakdown-history',
    title: 'ASSET BREAKDOWN HISTORY',
    category: 'maintenance',
    categoryLabel: 'Failure History',
    icon: Clock,
    color: '#f97316',
    description: 'Historical log of breakdown incidents, response times, and total downtime hours per asset.',
    fetcher: (params) => getGenericReportAdapter('asset-breakdown-history', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'downtime-repair-type',
    title: 'DOWNTIME BY REPAIR TYPE FOR EQUIPMENT',
    category: 'maintenance',
    categoryLabel: 'Repair Categories',
    icon: BarChart3,
    color: '#8b5cf6',
    description: 'Downtime hours broken down by repair type (Engine, Electrical, Hydraulics, Transmission, Undercarriage).',
    fetcher: (params) => getGenericReportAdapter('downtime-repair-type', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },

  // ── 4. Preventive Maintenance ──
  {
    id: 'pm-scheduler-report',
    title: 'PREVENTIVE MAINTENANCE SCHEDULER REPORT',
    category: 'pm_maintenance',
    categoryLabel: 'PM Calendar',
    icon: Calendar,
    color: '#10b981',
    description: 'Schedule calendar of upcoming preventive maintenance cycles across equipment.',
    fetcher: (params) => getGenericReportAdapter('pm-scheduler-report', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'open-pm-wo-list',
    title: 'OPEN PM WORK ORDERS LIST REPORT',
    category: 'pm_maintenance',
    categoryLabel: 'Open PM List',
    icon: Calendar,
    color: '#10b981',
    description: 'List of scheduled preventive maintenance work orders pending execution.',
    fetcher: (params) => getGenericReportAdapter('open-pm-wo-list', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'wo-pm-plan',
    title: 'WORK ORDER PM PLAN REPORTS',
    category: 'pm_maintenance',
    categoryLabel: 'PM Master Plan',
    icon: Layers,
    color: '#3b82f6',
    description: 'Master PM schedule mapping asset groups to frequency cycles (Monthly, Quarterly, Annual).',
    fetcher: (params) => getGenericReportAdapter('wo-pm-plan', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'checklist-wo-summary',
    title: 'CHECKLIST WORKORDER SUMMARY',
    category: 'pm_maintenance',
    categoryLabel: 'Checklist Audits',
    icon: FileCheck,
    color: '#6366f1',
    description: 'Summary of maintenance tickets completed using standardized inspection checklists.',
    fetcher: (params) => getGenericReportAdapter('checklist-wo-summary', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'deviation-report',
    title: 'DEVIATION REPORT',
    category: 'pm_maintenance',
    categoryLabel: 'Schedule Deviation',
    icon: AlertTriangle,
    color: '#d97706',
    description: 'Deviations between scheduled PM due dates and actual technician execution dates.',
    fetcher: (params) => getGenericReportAdapter('deviation-report', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'inventory-upcoming-pm',
    title: 'INVENTORY FOR UPCOMING SCHEDULED MAINTENANCE',
    category: 'pm_maintenance',
    categoryLabel: 'PM Material Forecast',
    icon: Boxes,
    color: '#f59e0b',
    description: 'Forecast of spare parts and materials required for upcoming PM schedules.',
    fetcher: (params) => getGenericReportAdapter('inventory-upcoming-pm', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'suggested-vs-actual-date',
    title: 'SUGGESTED VS ACTUAL COMPLETION DATE REPORT',
    category: 'pm_maintenance',
    categoryLabel: 'SLA Delay Analysis',
    icon: Clock,
    color: '#f97316',
    description: 'Analysis of target completion dates versus actual closure timestamps.',
    fetcher: (params) => getGenericReportAdapter('suggested-vs-actual-date', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'wo-completion-maintenance',
    title: 'WORKORDER COMPLETION MAINTENANCE REPORT',
    category: 'pm_maintenance',
    categoryLabel: 'Completion Analytics',
    icon: CheckCircle2,
    color: '#22c55e',
    description: 'Maintenance completion metrics: completed on-time %, delayed %, and SLA score.',
    fetcher: (params) => getGenericReportAdapter('wo-completion-maintenance', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'closed-wo-completion-notes',
    title: 'CLOSED WORK ORDERS WITH COMPLETION NOTES',
    category: 'pm_maintenance',
    categoryLabel: 'Resolution Notes',
    icon: FileText,
    color: '#8b5cf6',
    description: 'Completed work orders with technician closure notes, replaced parts, and root cause notes.',
    fetcher: (params) => getGenericReportAdapter('closed-wo-completion-notes', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'site-asset-sm-summary',
    title: 'SITE ASSET AND SM SUMMARY',
    category: 'pm_maintenance',
    categoryLabel: 'PM Site Coverage',
    icon: Building2,
    color: '#14b8a6',
    description: 'Site-wise summary of assets assigned to scheduled preventive maintenance plans.',
    fetcher: (params) => getGenericReportAdapter('site-asset-sm-summary', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'scheduled-maint-summary',
    title: 'SCHEDULED MAINTENANCE SUMMARY REPORT',
    category: 'pm_maintenance',
    categoryLabel: 'PM Master Summary',
    icon: Calendar,
    color: '#0ea5e9',
    description: 'Macro overview of all scheduled PM programs enterprise-wide.',
    fetcher: (params) => getGenericReportAdapter('scheduled-maint-summary', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },

  // ── 5. Inventory & Materials ──
  {
    id: 'current-inventory',
    title: 'CURRENT INVENTORY REPORT',
    category: 'inventory',
    categoryLabel: 'Stock Valuation',
    icon: Layers,
    color: '#f59e0b',
    description: 'Complete stock balances, unit costs, location stores, and total inventory valuation (₹).',
    fetcher: (params) => getGenericReportAdapter('current-inventory', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'category'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'low-inventory',
    title: 'LOW INVENTORY REPORT',
    category: 'inventory',
    categoryLabel: 'Stockout Warning',
    icon: AlertTriangle,
    color: '#ef4444',
    description: 'SKUs at or below minimum reorder thresholds requiring urgent replenishment.',
    fetcher: (params) => getGenericReportAdapter('low-inventory', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'category-current-inventory',
    title: 'CATEGORY WISE CURRENT INVENTORY',
    category: 'inventory',
    categoryLabel: 'Category Balances',
    icon: Boxes,
    color: '#0ea5e9',
    description: 'Stock valuation and item counts grouped by material category.',
    fetcher: (params) => getGenericReportAdapter('category-current-inventory', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'spare-inventories',
    title: 'SPARE INVENTORIES REPORT',
    category: 'inventory',
    categoryLabel: 'Machinery Spares',
    icon: Wrench,
    color: '#6366f1',
    description: 'Dedicated inventory register for heavy machinery spare parts and consumables.',
    fetcher: (params) => getGenericReportAdapter('spare-inventories', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'inventory-history',
    title: 'INVENTORY HISTORY REPORT',
    category: 'inventory',
    categoryLabel: 'Stock Ledger',
    icon: Clock,
    color: '#8b5cf6',
    description: 'Audit log of stock receipts, site issues, returns, and adjustments.',
    fetcher: (params) => getGenericReportAdapter('inventory-history', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'category-available-inventory',
    title: 'CATEGORY WISE AVAILABLE INVENTORY REPORT',
    category: 'inventory',
    categoryLabel: 'Unreserved Stock',
    icon: CheckCircle2,
    color: '#10b981',
    description: 'Net available stock balances excluding reserved items for active work orders.',
    fetcher: (params) => getGenericReportAdapter('category-available-inventory', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'cycle-count-summary',
    title: 'CYCLE COUNT SUMMARY',
    category: 'inventory',
    categoryLabel: 'Physical Audit',
    icon: FileCheck,
    color: '#84cc16',
    description: 'Physical audit variance summary comparing system quantities against store counts.',
    fetcher: (params) => getGenericReportAdapter('cycle-count-summary', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'inventory-issue',
    title: 'INVENTORY ISSUE REPORT',
    category: 'inventory',
    categoryLabel: 'Store Dispatches',
    icon: ShoppingCart,
    color: '#ec4899',
    description: 'Material issues from site stores to technicians, equipment, and work orders.',
    fetcher: (params) => getGenericReportAdapter('inventory-issue', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'inventory-usage-history',
    title: 'INVENTORY USAGE HISTORY',
    category: 'inventory',
    categoryLabel: 'Consumption Velocity',
    icon: TrendingUp,
    color: '#14b8a6',
    description: 'Historical material consumption trend lines over custom date ranges.',
    fetcher: (params) => getGenericReportAdapter('inventory-usage-history', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'employee-wise-inventory',
    title: 'EMPLOYEE WISE INVENTORY REPORT',
    category: 'inventory',
    categoryLabel: 'Asset Custody',
    icon: Users,
    color: '#3b82f6',
    description: 'Inventory items, field tools, and safety gear issued to individual employees.',
    fetcher: (params) => getGenericReportAdapter('employee-wise-inventory', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'stock_variance',
    title: 'STOCK VARIANCE & RECONCILIATION',
    category: 'inventory',
    categoryLabel: 'Inventory & Risk',
    icon: Boxes,
    color: '#ef4444',
    description: 'Physical vs system stock variance values (₹), high-risk anomaly flags, and suggested inter-site transfers.',
    fetcher: getStockVarianceReport,
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'consumables_burn',
    title: 'CONSUMABLES & MATERIAL BURN RATE',
    category: 'inventory',
    categoryLabel: 'Consumables',
    icon: Flame,
    color: '#f97316',
    description: 'Monitor stock consumption velocity, calculate monthly burn rates, and predict stockout risk timelines.',
    fetcher: getConsumablesBurnReport,
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },

  // ── 6. Procurement & Purchase ──
  {
    id: 'open-purchase-request',
    title: 'OPEN PURCHASE REQUEST',
    category: 'procurement',
    categoryLabel: 'Pending PRs',
    icon: Clock,
    color: '#f59e0b',
    description: 'Purchase requisitions submitted by site engineers pending manager review.',
    fetcher: (params) => getGenericReportAdapter('open-purchase-request', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'all-purchase-request',
    title: 'ALL PURCHASE REQUEST',
    category: 'procurement',
    categoryLabel: 'PR Master',
    icon: FileText,
    color: '#3b82f6',
    description: 'Master purchase request register with approval stage and requested item breakdown.',
    fetcher: (params) => getGenericReportAdapter('all-purchase-request', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'pending-rfq',
    title: 'PENDING RFQ',
    category: 'procurement',
    categoryLabel: 'RFQ Tenders',
    icon: FileCheck,
    color: '#06b6d4',
    description: 'Requests for Quotation issued to vendors awaiting price submissions.',
    fetcher: (params) => getGenericReportAdapter('pending-rfq', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'quote-received-rfq',
    title: 'QUOTE RECEIVED RFQ',
    category: 'procurement',
    categoryLabel: 'Vendor Quotes',
    icon: DollarSign,
    color: '#10b981',
    description: 'Vendor quote comparisons evaluated for lowest price and lead time compliance.',
    fetcher: (params) => getGenericReportAdapter('quote-received-rfq', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'all-rfq',
    title: 'ALL RFQ',
    category: 'procurement',
    categoryLabel: 'RFQ Register',
    icon: Layers,
    color: '#8b5cf6',
    description: 'Complete historical RFQ register with tender status and awarded vendor details.',
    fetcher: (params) => getGenericReportAdapter('all-rfq', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'po-waiting-approval',
    title: 'WAITING FOR APPROVAL PURCHASE ORDER',
    category: 'procurement',
    categoryLabel: 'PO Approvals',
    icon: ShieldAlert,
    color: '#ef4444',
    description: 'Purchase Orders pending management approval with financial authority thresholds.',
    fetcher: (params) => getGenericReportAdapter('po-waiting-approval', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'po-approved',
    title: 'APPROVED PURCHASE ORDER',
    category: 'procurement',
    categoryLabel: 'Approved POs',
    icon: CheckCircle2,
    color: '#22c55e',
    description: 'Approved POs issued to vendors awaiting delivery and GRN generation.',
    fetcher: (params) => getGenericReportAdapter('po-approved', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'all-purchase-order',
    title: 'ALL PURCHASE ORDER',
    category: 'procurement',
    categoryLabel: 'PO Master',
    icon: ShoppingCart,
    color: '#6366f1',
    description: 'Complete Purchase Order register with PO value, vendor details, and fulfillment status.',
    fetcher: (params) => getGenericReportAdapter('all-purchase-order', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'all-receipt-grn',
    title: 'ALL RECEIPT / GRN',
    category: 'procurement',
    categoryLabel: 'Goods Receipt',
    icon: FileCheck,
    color: '#84cc16',
    description: 'Goods Receipt Notes (GRN) audit log verifying physical delivery against PO line items.',
    fetcher: (params) => getGenericReportAdapter('all-receipt-grn', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'inventory-purchase-transactions',
    title: 'INVENTORY PURCHASE TRANSACTIONS',
    category: 'procurement',
    categoryLabel: 'Purchase Ledger',
    icon: DollarSign,
    color: '#a855f7',
    description: 'Detailed purchase ledger for store inventory procurement spend.',
    fetcher: (params) => getGenericReportAdapter('inventory-purchase-transactions', params),
    permission: 'reports.procurement',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'po-history',
    title: 'PURCHASE ORDER HISTORY REPORT',
    category: 'procurement',
    categoryLabel: 'PO Audit Trail',
    icon: Clock,
    color: '#f97316',
    description: 'Full PO lifecycle: Created -> Approved -> Issued -> Partial GRN -> Full GRN -> Closed.',
    fetcher: (params) => getGenericReportAdapter('po-history', params),
    permission: 'reports.procurement',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'vendor-performance-dashboard',
    title: 'VENDOR PERFORMANCE DASHBOARD',
    category: 'procurement',
    categoryLabel: 'Vendor Scorecard',
    icon: Building2,
    color: '#10b981',
    description: 'Vendor evaluation matrix: delivery lead times, order fulfillment rate %, and price variance.',
    fetcher: (params) => getGenericReportAdapter('vendor-performance-dashboard', params),
    permission: 'reports.procurement',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'procurement_pipeline',
    title: 'PROCUREMENT & PO FULFILLMENT',
    category: 'procurement',
    categoryLabel: 'Procurement',
    icon: ShoppingCart,
    color: '#ec4899',
    description: 'Track purchase order lead times, fulfillment cycle days, and cost variance against approved budgets.',
    fetcher: getProcurementPipelineReport,
    permission: 'reports.procurement',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'payable-report',
    title: 'PAYABLE REPORT',
    category: 'procurement',
    categoryLabel: 'Accounts Payable',
    icon: DollarSign,
    color: '#d97706',
    description: 'Vendor invoice payables, outstanding balances, due dates, and aging analysis.',
    fetcher: (params) => getGenericReportAdapter('payable-report', params),
    permission: 'reports.financial',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },

  // ── 7. Logistics & Asset Movement ──
  {
    id: 'freight_logistics',
    title: 'FREIGHT & LOGISTICS OPTIMIZATION',
    category: 'logistics',
    categoryLabel: 'Logistics',
    icon: Truck,
    color: '#14b8a6',
    description: 'Analyze inter-site transfer routes, transit lead times, freight expenditures (₹), and route efficiency matrix.',
    fetcher: getFreightLogisticsReport,
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'heatmap',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-movement-tracking',
    title: 'ASSET MOVEMENT TRACKING REPORT',
    category: 'logistics',
    categoryLabel: 'Movement History',
    icon: Activity,
    color: '#0ea5e9',
    description: 'Real-time and historical GPS/RFID movement trail for high-value mobile assets.',
    fetcher: (params) => getGenericReportAdapter('asset-movement-tracking', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-movement-summary',
    title: 'ASSET MOVEMENT SUMMARY REPORT',
    category: 'logistics',
    categoryLabel: 'Relocation Analytics',
    icon: Truck,
    color: '#06b6d4',
    description: 'Aggregated relocation metrics: total inter-site transfers, average transit duration, and transfer costs.',
    fetcher: (params) => getGenericReportAdapter('asset-movement-summary', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-movement-report',
    title: 'ASSET MOVEMENT REPORT',
    category: 'logistics',
    categoryLabel: 'Transfers & Relocations',
    icon: Truck,
    color: '#14b8a6',
    description: 'Track asset movements between sites, departments, and custodians with approval status.',
    fetcher: (params) => getGenericReportAdapter('asset-movement-report', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-move-out',
    title: 'ASSET MOVE OUT REPORT',
    category: 'logistics',
    categoryLabel: 'Outbound Gate Pass',
    icon: Truck,
    color: '#f97316',
    description: 'Outbound asset movement permits, dispatching site, destination site, and authorizing officer.',
    fetcher: (params) => getGenericReportAdapter('asset-move-out', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-move-out-return',
    title: 'MOVE OUT RETURN',
    category: 'logistics',
    categoryLabel: 'Gate Passes',
    icon: Tag,
    color: '#f59e0b',
    description: 'Track equipment moved out of site locations and monitor return compliance timelines.',
    fetcher: (params) => getGenericReportAdapter('asset-move-out-return', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'location-wise-dispatch',
    title: 'LOCATION WISE DISPATCH REPORT',
    category: 'logistics',
    categoryLabel: 'Dispatches',
    icon: Truck,
    color: '#8b5cf6',
    description: 'Equipment dispatched from each site location with carrier details and gate pass codes.',
    fetcher: (params) => getGenericReportAdapter('location-wise-dispatch', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'location-wise-dispatch-journey',
    title: 'LOCATION WISE DISPATCH JOURNEY REPORT',
    category: 'logistics',
    categoryLabel: 'Dispatch Lifecycle',
    icon: TrendingUp,
    color: '#3b82f6',
    description: 'Complete dispatch lifecycle: Request -> Approval -> Dispatch -> In-Transit -> Receipt -> Closure.',
    fetcher: (params) => getGenericReportAdapter('location-wise-dispatch-journey', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'location-wise-asset-count',
    title: 'LOCATION WISE ASSET COUNT',
    category: 'logistics',
    categoryLabel: 'Location Counts',
    icon: MapPin,
    color: '#10b981',
    description: 'Total active asset counts distributed by site location and physical yard.',
    fetcher: (params) => getGenericReportAdapter('location-wise-asset-count', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'rfid-asset-tracking',
    title: 'RFID ASSET TRACKING',
    category: 'logistics',
    categoryLabel: 'RFID Audits',
    icon: Radio,
    color: '#ec4899',
    description: 'RFID scan verification: matched scans, missing scans, scanner location, and last seen timestamp.',
    fetcher: (params) => getGenericReportAdapter('rfid-asset-tracking', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'location-wise-asset-scan',
    title: 'ASSET LOCATION WISE SCAN REPORT',
    category: 'logistics',
    categoryLabel: 'Location Scans',
    icon: MapPin,
    color: '#0ea5e9',
    description: 'RFID and GPS scan density grouped by site location and physical zone.',
    fetcher: (params) => getGenericReportAdapter('location-wise-asset-scan', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'product-wise-dispatch',
    title: 'PRODUCT WISE DISPATCH REPORT',
    category: 'logistics',
    categoryLabel: 'Product Logistics',
    icon: Boxes,
    color: '#14b8a6',
    description: 'Equipment dispatches grouped by product model and equipment classification.',
    fetcher: (params) => getGenericReportAdapter('product-wise-dispatch', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'theft-protection-history',
    title: 'ASSET THEFT PROTECTION HISTORY REPORT',
    category: 'logistics',
    categoryLabel: 'Security Alerts',
    icon: ShieldAlert,
    color: '#ef4444',
    description: 'Un-authorized movement alerts, geofence breaches, and security incident resolution logs.',
    fetcher: (params) => getGenericReportAdapter('theft-protection-history', params),
    permission: 'reports.security',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },

  // ── 8. Safety, Compliance & Warranty ──
  {
    id: 'audit_compliance',
    title: 'AUDIT COMPLIANCE & GEOFENCING',
    category: 'safety',
    categoryLabel: 'Governance & Audits',
    icon: ShieldCheck,
    color: '#22c55e',
    description: 'Audit assignment completion rates, SLA breach statuses, geofence verification pass rates, and completion selfies.',
    fetcher: getAuditComplianceReport,
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'statutory_compliance',
    title: 'STATUTORY & FITNESS COMPLIANCE',
    category: 'safety',
    categoryLabel: 'Statutory Docs',
    icon: FileCheck,
    color: '#84cc16',
    description: 'Monitor expiration timelines for insurance, fitness certificates, road tax, and PUC permits across fleets.',
    fetcher: getStatutoryComplianceReport,
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'warranty_radar',
    title: 'WARRANTY RADAR & EXPIRY TRACKER',
    category: 'safety',
    categoryLabel: 'Warranty Lifecycle',
    icon: Calendar,
    color: '#a855f7',
    description: 'Filter warranties expiring within 60 days to prevent unclaimable repair costs and claim warranty coverage.',
    fetcher: getWarrantyRadarReport,
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'operator_safety',
    title: 'OPERATOR & EQUIPMENT SAFETY SCORE',
    category: 'safety',
    categoryLabel: 'Safety Audits',
    icon: HardHat,
    color: '#d97706',
    description: 'Evaluate checklist safety audit results, critical violation penalties, and overall operator safety scores.',
    fetcher: getOperatorSafetyReport,
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'gauge',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'asset-expiry-warranty',
    title: 'ASSET EXPIRY WARRANTY',
    category: 'safety',
    categoryLabel: 'Warranty Status',
    icon: ShieldCheck,
    color: '#a855f7',
    description: 'Warranties expiring soon or already expired across active equipment.',
    fetcher: getWarrantyRadarReport,
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'warranty-dashboard',
    title: 'WARRANTY DASHBOARD',
    category: 'safety',
    categoryLabel: 'Warranty Exposure',
    icon: Calendar,
    color: '#ec4899',
    description: 'Active warranties, warranties expiring in 30/60 days, expired warranties, and claim opportunities.',
    fetcher: getWarrantyRadarReport,
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },

  // ── 9. Fleet & Vehicles ──
  {
    id: 'vehicle-tracking-quick',
    title: 'VEHICLE TRACKING QUICK REPORT',
    category: 'fleet',
    categoryLabel: 'Fleet Quick',
    icon: Truck,
    color: '#06b6d4',
    description: 'Fleet operational status: active, moving, idle, offline, and total distance (km).',
    fetcher: (params) => getGenericReportAdapter('vehicle-tracking-quick', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'pie',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'vehicle-tracking-details',
    title: 'VEHICLE TRACKING DETAILS REPORT',
    category: 'fleet',
    categoryLabel: 'Fleet Details',
    icon: FileText,
    color: '#6366f1',
    description: 'Detailed vehicle telemetry: driver, GPS location, speed, fuel level, and status.',
    fetcher: (params) => getGenericReportAdapter('vehicle-tracking-details', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'vehicle-booking-log',
    title: 'VEHICLE BOOKING LOG REPORT',
    category: 'fleet',
    categoryLabel: 'Vehicle Reservations',
    icon: Calendar,
    color: '#8b5cf6',
    description: 'Vehicle booking logs, requesting department, driver assignment, and trip duration.',
    fetcher: (params) => getGenericReportAdapter('vehicle-booking-log', params),
    permission: 'reports.view',
    supportedFilters: ['site', 'dateRange'],
    visualization: 'line',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
  {
    id: 'vehicle-booking-status',
    title: 'VEHICLE BOOKING STATUS',
    category: 'fleet',
    categoryLabel: 'Booking Status',
    icon: CheckCircle2,
    color: '#10b981',
    description: 'Status of vehicle booking requests (Requested, Approved, Active, Completed, Cancelled).',
    fetcher: (params) => getGenericReportAdapter('vehicle-booking-status', params),
    permission: 'reports.view',
    supportedFilters: ['site'],
    visualization: 'bar',
    exportFormats: ['pdf', 'xlsx', 'csv', 'print'],
  },
]
